### ISSUE TITLE
32-bit x86 version?

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [incinirate/Riko4#10]
That's the type of PC I have at hand

**Comment by incinirate** [comment]
Compile it yourself, 99% of people use 64bit and that's good enough for me.

**Comment by StinkerB06** [comment]
Dumb shit I don't have options for compiling.

**Comment by StinkerB06** [comment]
Finding simple solutions on Google for compiling is not an easy task

**Comment by The-Beesh-Spweesh** [comment]
Compile it yourself, 90% of programs support 32-bit Windows and that's good enough for me.
