### ISSUE TITLE
Rework Audio Library

### ISSUE THREAD

**Issue by incinirate** [incinirate/Riko4#17]
The current audio system is too limited. Also add a sound fx / music editor

**Comment by StinkerB06** [comment]
You're still not supporting 32-bit windows?

**Comment by CrazedProgrammer** [comment]
Any concrete ideas for improvements?
I think the audio system is good enough as it is. One minor nuisance i encounter is that some parameters (like `attack`) are not optional when they should be.

One idea for the music/sound editor is for it to be compatible with pre-existing formats like NSF (NES music format).

**Comment by incinirate** [comment]
I think the current system is great for some things, music for example works fine in the queue format, but for others, like arbitrary sound FX, the limitation of one active sound per channel at a time makes it difficult. For example, in the `part` demo, the ship's exhaust, and the explosion sound effect use the same channel (noise), and so only one can be active at a time, which is very distracting.

**Comment by incinirate** [comment]
Also yes, I intended to make almost all parameters optional for audio, excluding channel, frequency, and time. Just haven't gotten around to it. I might revisit audio sometime this week.

**Comment by incinirate** [comment]
The rest of the parameters were made optional in f17bbcedb5bae7cb4eea7a366fc88a3664d4c3f6, I'll be looking into expanding the audio system next.
