### ISSUE TITLE
Using max GLSL version on Nix does not work

### ISSUE THREAD

**Issue by CrazedProgrammer** [incinirate/Riko4#28]
![](https://i.crzd.me/7BxoevPs.png)

This results in a white non-interactive window being displayed.
When I hardcode the line https://github.com/incinirate/Riko4/blob/master/src/core/shader.cpp#L45 to use version 120 it works again.

**Comment by incinirate** [comment]
Hm, some others had issues with version 120, although I guess always using maxgl will open problems like these, what do you think about having a cmdline flag to set glsl version?

**Comment by CrazedProgrammer** [comment]
That would work! The flag could then be added to the wrapper script at https://github.com/incinirate/Riko4/blob/master/default.nix#L50.

**Comment by incinirate** [comment]
742cf4f Should fix this issue, thanks!

**Comment by Lignum** [comment]
Why is this `#version 450`? If you're using `gl_FragColor`, it should be `#version 120` at most, it's deprecated beyond that.

> Hm, some others had issues with version 120,

This is the real issue that needs fixing. Can you elaborate?

**Comment by incinirate** [comment]
I've since reverted the default back to `#120`.
