### ISSUE TITLE
Problem with compilation on MacOS

### ISSUE THREAD

**Issue by Muhtasim-Rasheed** [incinirate/Riko4#38]
So, when I was compiling Riko4, I got the following error with cmake:
`-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
<FindSDL2.cmake>
</FindSDL2.cmake>
-- Found SDL2: /Library/Frameworks/SDL2.framework;-framework Cocoa
-- Found LuaJIT: /usr/local/lib/libluajit-5.1.dylib
<FindSDL2_gpu.cmake>
</FindSDL2_gpu.cmake>
-- Found SDL2_gpu: /usr/local/lib/SDL2_gpu.framework;-framework Cocoa
-- Found CURL: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/lib/libcurl.tbd (found version "7.77.0")
-- Found CURLpp: /usr/local/lib/libcurlpp.dylib
-- Configuring done (2.2s)
-- Generating done (0.1s)
-- Build files have been written to: /Users/mnarasheed/riko4/build
[  6%] Building CXX object CMakeFiles/riko4.dir/src/core/events.cpp.o
clang: warning: argument unused during compilation: '-pagezero_size 10000' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-image_base 100000000' [-Wunused-command-line-argument]
[ 13%] Building CXX object CMakeFiles/riko4.dir/src/core/luaMachine.cpp.o
clang: warning: argument unused during compilation: '-pagezero_size 10000' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-image_base 100000000' [-Wunused-command-line-argument]
[ 20%] Building CXX object CMakeFiles/riko4.dir/src/core/rikoProcess.cpp.o
clang: warning: argument unused during compilation: '-pagezero_size 10000' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-image_base 100000000' [-Wunused-command-line-argument]
In file included from /Users/mnarasheed/riko4/src/core/rikoProcess.cpp:7:
/Users/mnarasheed/riko4/libs/include/getopt.h:16:10: fatal error: 'crtdefs.h' file not found
#include <crtdefs.h>
         ^~~~~~~~~~~
1 error generated.`
I would appreciate any help

Thanks.

**Comment by emmachase** [comment]
Fixed in 19be3f9d3140807af282b5244fa486aa93816b75
