### ISSUE TITLE
Can't open menu in paint

### ISSUE THREAD

**Issue by Lignum** [incinirate/Riko4#5]
I can't press ctrl to open the menu in paint. This works fine in edit.

**Comment by incinirate** [comment]
Paint is really old and bad, use "ink" to draw, it has lots more features, is faster, looks nicer, and is being maintained. However, I suspect that the issue with paint is that i forgot to uncapitalize "ctrl" in the event loop.

**Comment by Lignum** [comment]
Oh yeah, ink works perfectly.
