### ISSUE TITLE
Changing Pallettes

### ISSUE THREAD

**Issue by incinirate** [incinirate/Riko4#6]
The ability to change the rgb values of the 16 given colors was always intended, it's been delayed over 1 hiccup, Images. Because Images are actually just textures that get rendered and don't actually store the original 1-16 color values associated at each pixel, how would images know how or when to update? A similar issue would be just the colors already drawn to the screen, which isn't a huge issue I supposed that the call to the color changing api could just invoke a screen clear or something. Anyone have thoughts?

**Comment by Lemmmy** [comment]
palette update hook

**Comment by incinirate** [comment]
Like a `myImage.paletteUpdated = function(newPalette) --[[do shiz]] end` callback kind of thing?

**Comment by incinirate** [comment]
I'm not a particularly huge fan of this solution, but one idea is to store the 1-16 map alongside the SDL Surface so that when the palette does get updated, it knows how to update the texture... not very elegant and may double the ram required for an image but all the other solutions I can think of wouldn't work well / would just be a pain.
